// <auto-generated />
namespace ConnectDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user_add_column_note : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_add_column_note));
        
        string IMigrationMetadata.Id
        {
            get { return "202106211022546_user_add_column_+note+"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
